# Generated by Django 5.2 on 2025-06-26 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tree_menu", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="menuitem",
            options={},
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="named_url",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
